"""Protein metadata endpoint — UniProt info + external DB links for a gene."""

from __future__ import annotations

from fastapi import APIRouter

from ...domain.protein_info import get_protein_info
from ...schemas import ProteinInfo

router = APIRouter(prefix="/api/v1", tags=["proteins"])


@router.get("/proteins/{gene}", response_model=ProteinInfo)
def get_protein(gene: str, lang: str = "ko") -> ProteinInfo:
    """Protein info (UniProt + local-LLM bullet summary) for a human gene symbol.

    The summary is generated by the local LLM in the requested language
    (lang="ko" → Korean 개조식, lang="en" → English bullets), summarized directly
    from the English UniProt function — English is not a re-translation of the
    Korean. Both languages are cached separately (first click per language shows
    a shimmer). Always 200s (found=false → search links).
    """
    return ProteinInfo.model_validate(get_protein_info(gene, lang=lang))
